### ISSUE TITLE
AI聊天需求

### ISSUE THREAD

**Issue by shieryue1** [xidchen/DG#2]
一、大致流程
1、主动给对方打招呼
2、和对方聊几句（介绍项目，确认用户是否感兴趣）
3、感兴趣就发送指定的联系方式（链接、号码）

二、通常聊天逻辑
1、打招呼话术多变，尽量每个都不一样
2、介绍本次沟通的目的，话术带有引导性，引导客户说Yes/No
3、通过来回的沟通（如了解客户基础信息，以及回答客户关于项目方面的问题）来确认客户是否有意愿参与（项目内容接单后，会有话术喂养）
4、客户有意愿的话，就发送三方的联系方式（社媒号码或者号码链接，三方提供）

备注：
1、任意阶段客户不回复了，我们就不主动再发了
2、任意阶段客户表达No的意思，AI将以友好和抱歉的姿态结束聊天
3、客户聊天偏离了主题时，我们的话术要引导到我们的目的上去（如：客户说，很高兴认识你，我可以看你的照片吗？我们就要讲话题引导到主题：谢谢你的喜欢，但是先让我们一起完成现在最重要的事情，有机会的话，我想我们可以成为朋友）

**Comment by xidchen** [comment]
关于系统设计有什么想法，包括但不限于比如该系统里你方做哪一部分，需要我方做哪一部分，双方之间的交互界面有哪些成分。

**Comment by shieryue1** [comment]
1、我方提供聊天记录，记录中会带上双方的标识，已保证对话的完整性和独立性。
2、你方对聊天内容进行连贯的语义识别，并根据目的推动生成对话，推动对话达到目的
3、我们会根据客户情况和需求，提前给到聊天目的、产品信息，以便于AI生成内容
4、要发给客户的联系方式，你生成内容后，用占位符，我们这边统一替换即可（链接/号码）两种形式
5、前期你需要语料的话，我这边可以准备提供给你，你给一下文本规范或者前端页面

**Comment by xidchen** [comment]
请提供一些语料，另外对于聊天语言有什么要求。

**Comment by shieryue1** [comment]
[Uploading 训练话术13种.zip…]()
